#!/bin/sh -e

test -n "${DOCKER_HUB_REPOSITORY}" || ( echo "DOCKER_HUB_REPOSITORY is not defined!" && false )

RESPONSE="$(curl -sL https://registry.hub.docker.com/v2/repositories/${DOCKER_HUB_REPOSITORY}/tags)"

echo "${RESPONSE}" | jq

LATEST_PUSHED_VERSION="$(echo "${RESPONSE}" | jq -r '.results[].name' | sort -Vr | grep -oE '^[0-9]+\.[0-9]+$' | head -n 1 | tr -d '\n')"

test -n "${LATEST_PUSHED_VERSION}" || ( echo "LATEST_PUSHED_VERSION is not found!" && false )

echo "::set-output name=version::${LATEST_PUSHED_VERSION}"
echo "Latest Version: ${LATEST_PUSHED_VERSION}"
