apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "single-page-application-server.fullname" . }}
  labels:
    {{- include "single-page-application-server.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{- toYaml .Values.config | nindent 4 }}
