{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "single-page-application-server.fullname" . | quote}}
  labels:
    {{- include "single-page-application-server.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "single-page-application-server.selectorLabels" . | nindent 6 }}
  policyTypes:
    {{- toYaml .Values.networkPolicy.policyTypes | nindent 4 }}
  ingress:
    {{- toYaml .Values.networkPolicy.ingress | nindent 4 }}
  egress:
    {{- toYaml .Values.networkPolicy.egress | nindent 4 }}
{{- end -}}
