#!/bin/sh -e

TARGET_IMAGE="$1"
BASE_IMAGE="$2"

test -n "${BASE_IMAGE}" || ( echo "BASE_IMAGE is not specified" && false )
test -n "${TARGET_IMAGE}" || ( echo "TARGET_IMAGE is not specified" && false )

set -x
docker pull -q "${BASE_IMAGE}"
docker pull -q "${TARGET_IMAGE}"

/contains-all-layers-of "${1}" "${2}" && \
  echo '::set-output name=needs_update::false' || \
  echo '::set-output name=needs_update::true'
